### PR TITLE
Improve look up of VDM-SL types

### PR DESCRIPTION
**Pull request by peterwvj**
Addresses #676

### CODE REVIEW

**Comment by nickbattle** [comment]
The reason this fails is that module Environments are specific to a particular module, and the getGlobalEnvironment call is returning an environment for the default module - ie. B. But of course the G'T type is not visible from B.

It would be best if the Environment generated in the ValueFactory was for where the ValueFactory method was called from. But that information is not available, and I can't see a simple way to add it without changing the native call system significantly.

The approach in the pull request tries the default module and then searches the definitions in the module named. That makes some sense, but I think a neater way to do this would be to provide a getGlobalEnvironment(String module) overload, to specify the module you want. This would be a one-liner, calling findModule. That could then replace the getGlobalEnvironment() call in getType and the rest of the method would remain more or less the same - the 2nd argument to findType would presumably also be "module", though that doesn't seem to be used by findType(?).

**Comment by peterwvj** [comment]
@nickbattle Alright, so I tried to implement the fix based on your suggestions. Could you take a look again and confirm that it looks OK.

Thanks!

**Comment by nickbattle** [comment]
Yes PJ, that looks perfect.

**Comment by peterwvj** [comment]
Great, thanks a lot, Nick.

**Pull request merged**
